function build_simulink_model(PARAM)
% BUILD_SIMULINK_MODEL
% Builds the lower-limb exoskeleton gait-tracking Simulink model.
%
% Usage:
%   build_simulink_model()
%   build_simulink_model(PARAM)
%
% Outputs:
%   models/exoskeleton_gait_system.slx
%
% Plant:
%   J*theta_ddot + B*theta_dot + K*theta = tau + tau_dist
%
% Angles are in radians and torque is in N*m.

    %% 1. Resolve project paths and parameters
    script_dir = fileparts(mfilename('fullpath'));
    project_root = fileparts(script_dir);

    if nargin < 1 || isempty(PARAM)
        param_file = fullfile(project_root, 'scripts', 'project_parameters.m');

        if ~isfile(param_file)
            error('build_simulink_model:MissingParameters', ...
                'Cannot find parameter file: %s', param_file);
        end

        run(param_file);

        if ~exist('PARAM', 'var')
            error('build_simulink_model:MissingPARAM', ...
                'project_parameters.m did not create PARAM.');
        end
    end

    required_fields = {'simulation', 'gait', 'joint', 'pid', ...
        'actuator', 'disturbance'};

    for k = 1:numel(required_fields)
        if ~isfield(PARAM, required_fields{k})
            error('build_simulink_model:MissingField', ...
                'PARAM.%s is missing.', required_fields{k});
        end
    end

    models_dir = fullfile(project_root, 'models');

    if ~isfolder(models_dir)
        mkdir(models_dir);
    end

    model_name = 'exoskeleton_gait_system';
    model_file = fullfile(models_dir, [model_name, '.slx']);

    %% 2. Close an already loaded model without saving stale changes
    if bdIsLoaded(model_name)
        close_system(model_name, 0);
    end

    %% 3. Create model and configure solver
    new_system(model_name);

    cleanup_model = onCleanup(@() local_close_model(model_name));

    set_param(model_name, ...
        'SolverType', 'Fixed-step', ...
        'Solver', 'ode4', ...
        'FixedStep', num2str(PARAM.simulation.Ts, '%.15g'), ...
        'StartTime', '0', ...
        'StopTime', num2str(PARAM.simulation.time, '%.15g'), ...
        'SaveTime', 'on', ...
        'TimeSaveName', 'tout', ...
        'SaveOutput', 'on', ...
        'OutputSaveName', 'yout');

    %% 4. Gait reference: sinusoid in radians
    add_block('simulink/Sources/Sine Wave', ...
        [model_name, '/Gait_Reference'], ...
        'Position', [45, 115, 85, 145], ...
        'Amplitude', num2str(PARAM.gait.amplitude_rad, '%.15g'), ...
        'Bias', num2str(PARAM.gait.offset_rad, '%.15g'), ...
        'Frequency', num2str(2*pi*PARAM.gait.frequency, '%.15g'), ...
        'Phase', '0', ...
        'SampleTime', '0');

    %% 5. Tracking error: desired minus actual
    add_block('simulink/Math Operations/Sum', ...
        [model_name, '/Error_Sum'], ...
        'Position', [155, 115, 180, 145], ...
        'Inputs', '+-');

    %% 6. PID controller with actuator saturation
    add_block('simulink/Continuous/PID Controller', ...
        [model_name, '/PID_Controller'], ...
        'Position', [230, 110, 295, 150], ...
        'P', num2str(PARAM.pid.Kp, '%.15g'), ...
        'I', num2str(PARAM.pid.Ki, '%.15g'), ...
        'D', num2str(PARAM.pid.Kd, '%.15g'), ...
        'N', num2str(PARAM.pid.N, '%.15g'), ...
        'LimitOutput', 'on', ...
        'UpperSaturationLimit', ...
            num2str(PARAM.actuator.max_torque, '%.15g'), ...
        'LowerSaturationLimit', ...
            num2str(PARAM.actuator.min_torque, '%.15g'));

    %% 7. Rectangular disturbance pulse
    % Disturbance = +magnitude at start_time and returns to zero
    % at end_time through the subtracting input of Disturbance_Sum.
    add_block('simulink/Sources/Step', ...
        [model_name, '/Dist_Start'], ...
        'Position', [220, 25, 255, 55], ...
        'Time', num2str(PARAM.disturbance.start_time, '%.15g'), ...
        'Before', '0', ...
        'After', num2str(PARAM.disturbance.magnitude, '%.15g'));

    add_block('simulink/Sources/Step', ...
        [model_name, '/Dist_End'], ...
        'Position', [220, 65, 255, 95], ...
        'Time', num2str(PARAM.disturbance.end_time, '%.15g'), ...
        'Before', '0', ...
        'After', num2str(PARAM.disturbance.magnitude, '%.15g'));

    add_block('simulink/Math Operations/Sum', ...
        [model_name, '/Disturbance_Sum'], ...
        'Position', [315, 40, 340, 75], ...
        'Inputs', '+-');

    %% 8. Applied torque plus disturbance
    add_block('simulink/Math Operations/Sum', ...
        [model_name, '/Torque_Sum'], ...
        'Position', [390, 115, 415, 145], ...
        'Inputs', '++');

    %% 9. Exoskeleton plant
    denominator = sprintf('[%.15g %.15g %.15g]', ...
        PARAM.joint.inertia, ...
        PARAM.joint.damping, ...
        PARAM.joint.stiffness);

    add_block('simulink/Continuous/Transfer Fcn', ...
        [model_name, '/Exoskeleton_Plant'], ...
        'Position', [470, 105, 575, 155], ...
        'Numerator', '[1]', ...
        'Denominator', denominator);

    %% 10. Output ports
    add_block('simulink/Sinks/Out1', ...
        [model_name, '/Theta_Actual'], ...
        'Position', [660, 105, 690, 125]);

    add_block('simulink/Sinks/Out1', ...
        [model_name, '/Theta_Desired'], ...
        'Position', [660, 170, 690, 190]);

    add_block('simulink/Sinks/Out1', ...
        [model_name, '/Tracking_Error'], ...
        'Position', [660, 225, 690, 245]);

    add_block('simulink/Sinks/Out1', ...
        [model_name, '/Control_Torque'], ...
        'Position', [660, 280, 690, 300]);

    %% 11. Scope
    add_block('simulink/Sinks/Scope', ...
        [model_name, '/Gait_Scope'], ...
        'Position', [500, 205, 540, 245], ...
        'NumInputPorts', '2');

    %% 12. Wire the model
    add_line(model_name, ...
        'Gait_Reference/1', 'Error_Sum/1', 'autorouting', 'on');

    add_line(model_name, ...
        'Gait_Reference/1', 'Theta_Desired/1', 'autorouting', 'on');

    add_line(model_name, ...
        'Gait_Reference/1', 'Gait_Scope/1', 'autorouting', 'on');

    add_line(model_name, ...
        'Error_Sum/1', 'PID_Controller/1', 'autorouting', 'on');

    add_line(model_name, ...
        'Error_Sum/1', 'Tracking_Error/1', 'autorouting', 'on');

    add_line(model_name, ...
        'Dist_Start/1', 'Disturbance_Sum/1', 'autorouting', 'on');

    add_line(model_name, ...
        'Dist_End/1', 'Disturbance_Sum/2', 'autorouting', 'on');

    add_line(model_name, ...
        'PID_Controller/1', 'Torque_Sum/1', 'autorouting', 'on');

    add_line(model_name, ...
        'PID_Controller/1', 'Control_Torque/1', 'autorouting', 'on');

    add_line(model_name, ...
        'Disturbance_Sum/1', 'Torque_Sum/2', 'autorouting', 'on');

    add_line(model_name, ...
        'Torque_Sum/1', 'Exoskeleton_Plant/1', 'autorouting', 'on');

    add_line(model_name, ...
        'Exoskeleton_Plant/1', 'Theta_Actual/1', 'autorouting', 'on');

    add_line(model_name, ...
        'Exoskeleton_Plant/1', 'Gait_Scope/2', 'autorouting', 'on');

    add_line(model_name, ...
        'Exoskeleton_Plant/1', 'Error_Sum/2', 'autorouting', 'on');

    %% 13. Update, save, and close
    set_param(model_name, 'SimulationCommand', 'update');

    save_system(model_name, model_file);

    fprintf('\nSimulink gait model built and saved:\n%s\n', model_file);
    fprintf('Solver: fixed-step ode4 | Step size: %.6g s\n', ...
        PARAM.simulation.Ts);
    fprintf('Simulation duration: %.6g s\n', ...
        PARAM.simulation.time);
end


function local_close_model(model_name)
% Close the model if an error occurs during construction.
    if bdIsLoaded(model_name)
        close_system(model_name, 0);
    end
end